article/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addarticle/',views.addArticle,name='addarticle'),
    path('article/<int:id>',views.detail,name='detail'),
    path('update/<int:id>',views.updateArticle,name='update'),
    path('delete/<int:id>',views.deleteArticle,name='delete'),
    path('',views.articles,name='articles'),
    path('comment/<int:id>',views.addComment,name='comment'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.loginUser,name='loginUser'),
    path('logout/',views.logoutUser,name='logoutUser'),
]

article/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Baslik")
    content = RichTextField()
    create_date = models.DateTimeField(auto_now_add=True,verbose_name="Olusturulma Tarihi")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye Gorsel Ekleyin")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="makale",related_name="comments")
    comment_author = models.CharField(max_length=20,verbose_name="isim")
    comment_content = models.CharField(max_length=150,verbose_name="yorum")
    comment_date = DateTimeField(auto_now_add=True,verbose_name="Olusturulma Tarihi")
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from django.forms import fields
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields=["title","content","article_image"]

user/forms.py
from django import forms
from django.forms.widgets import PasswordInput

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanici Adi")
    password = forms.CharField(label="Parola",widget=PasswordInput)


class registerForm(forms.Form):
    username = forms.CharField(max_length=20,label="Kullanici Adi")
    password = forms.CharField(max_length=30,label="Parola",widget=PasswordInput)
    confirm = forms.CharField(max_length=30,label="Parolayi Dogrula",widget=PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eslesmiyor")
        
        values = {
            "username":username,
            "password":password
        }
        return values

article/views.py
import article
from django.forms import models
from django.shortcuts import redirect, render,HttpResponse,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})

    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def index(request):
    context={
        "number1":1,
        "number2":2
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context={"articles":articles}
    return render(request,"dashboard.html",context)

@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user 
        article.save()

        messages.success(request,"Makale Basariyla Kaydedildi")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})


def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    
    comments = article.comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user 
        article.save()

        messages.success(request,"Makale Basariyla Guncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Silindi")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_content=comment_content,comment_author=comment_author)
        newComment.article = article

        newComment.save()
    
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django import forms
from django.shortcuts import render,redirect
from .forms import registerForm, LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout

def register(request):
    if request.method == "POST":
        form = registerForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            newUser = User(username=username)
            newUser.set_password(password)
            newUser.save()
            login(request,newUser)
            messages.success(request,"Basariyla Kayit Oldunuz")
            
            return redirect("index")
            
        form = registerForm()
        context = {"form":form }
        return render(request,"register.html",context)


    else:
        form = registerForm()
        context = {"form":form }
        return render(request,"register.html",context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {"form":form }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username,password=password)
        if user is None:
            messages.info(request,"Kullanici adi veya parola hatali")
            return render(request,"login.html",context)
            
        messages.success(request,"Basariyla Giris Yaptiniz")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)

    
def logoutUser(request):
    logout(request)
    messages.success(request,"Cikis Yaptiniz")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}
    <h3>Hakkimda</h3>
    <hr>    

    <p> DENEME DENEME DENEME </p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Olustur</h3>
    <hr>
    <form method="post" class="bootstrap4" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type = "submit" class="btn btn-primary">Makale Ekle</button>
    </form>
  </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}

    <div class="row">
        <div class="col-md-12 offset-md-3">
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
            </div>    
        </div>
    </div>
     <div class="row">
     <div class="col-md-12 offset-md-3">
            <div class="col-lg-8">
        <form>
            {% csrf_token %}
            <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Makale Ara...">
            <button type="submit" class="btn btn-success">Ara</button>
        </form>
        <hr>
    </div> </div> </div>
    {% if articles %}

        {% for article in articles %}
        <div  class="row">
            <div class="col-md-12 offset-md-3">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <form enctype="multipart/form-data">
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href="{% url 'article:detail' article.id %}"><h3 class="fw-bolder mb-1">{{article.title}}</h3></a>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.create_date}}</div>
                            <!-- Post Author-->
                            <hr>
                            <p>
                            Yazan,
                            {{article.author.username}}
                            </p>
                            
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                            <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
                        
                        {% endif %}
                        
                        <hr>
                        <!-- Post content-->
                        <p>
                            {{article.content|safe|truncatewords:40}}
                        </p>
                        <a style="float : right" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamini oku</a>
                    </form>
                    
                </div>
                
            </div>
        </div>
        {% endfor %}

    {% else %}
    <div class="row">
        <div class="col-md-12 offset-md-3">
            <div class="col-lg-8">
        <div class="alert alert-danger">Makale Bulunamadi</div> </div> </div> </div>
    {% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <h3>Kontrol Paneli</h3>
    <P>Hosgeldiniz, {{request.user.username}}</P>
    <hr>
    <a class="btn btn-danger" href="{% url 'article:addarticle'%}">Makale Ekle</a>
{% if articles %}

<table class="table">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Baslik</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Guncelle</th>
      <th scope="col">Sil</th>
    </tr>
    </thead>
 
    <tbody>

        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.create_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-primary">Guncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
    
    </tbody>
</table>
{% else %}

<div class = "alert alert-danger" >
    Henuz Makale Bulunmuyor
</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <form enctype="multipart/form-data">
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h3 class="fw-bolder mb-1">{{article.title}}</h3>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.create_date}}</div>
                            <!-- Post Author-->
                            <hr>
                            <p>
                            Yazan,
                            {{article.author.username}}
                            </p>
                            
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                        
                        {% endif %}
                        
                        <hr>
                        <!-- Post content-->
                        <section class="mb-5">
                            {{article.content|safe}}
                        </section>
                    </form>

                    <form method="post" action="{% url 'article:comment' article.id %}" class="mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Yorum Yap:</label>
                        <input name="comment_author" class="form-control" placeholder="Isminizi girin">
                    <textarea name="comment_content" class="form-control" rows="3" placeholder="Bir yorum birak.."></textarea>
                    <button class="btn btn-primary" id="button-search" type="submit">Yorum Yap</button>
                    </form>
                    </div>

                    {% if comments %}
                        {% for comment in comments %}
                            <div class="d-flex">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">{{comment.comment_author}}</div>
                                    <small>{{comment.comment_date}}</small> <br>
                                    {{comment.comment_content}}
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning">Yorum Yapilmamis</div>
                    {% endif %}

                </div>
                
            </div>



{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Tanju Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">Hakkimda</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
          </li>

        </ul>
        
        <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logoutUser' %}">Cikis Yap</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:loginUser' %}">Giris Yap</a>
          </li> 
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Kayit Ol</a>
          </li> 
        {% endif %}
        
          
          
        
        </ul>

      </div>
    </nav>

templates/includes/posttamplate.html
<div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on January 1, 2021 by Start Bootstrap</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>

templates/index.html
{% extends "layout.html" %}

{% block body %}
    
    <div class = "jumbotron text-center">
    <h3>Hosgeldiniz</h3>
    <p>Django deneme blogu</p>
    </div>
    <p>{{number1}} {{number2}}</p>

<P>
    {% if request.user.is_authenticated %}
        Giris Yapilmis
    {% else %}
    Giris Yapilmamis
    {% endif %}
</P>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Tanju Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %} 

    <div style ="margin-top:100px; margin-bottom:100px;" class = "container">

    {% if messages %}
        {% if message.tags == "info" %}
            <div class = "alert alert-danger">{{ message }}</div>
        {% else %}
        {% endif %}

        {% for message in messages %}
            <div class = "alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    
        {% endif %} 


        {% block body %}
        
        {% endblock body %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giris Yap</h3>
    <hr>
    <form method="post" class="bootstrap4">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class="btn btn-primary">Giris Yap</button>
    </form>
  </div>
</div>
    
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Kayit Ol</h3>
    <hr>
    <form method="post" class="bootstrap4">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class="btn btn-primary">Kayit Ol</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Guncelle</h3>
    <hr>
    <form method="post" class="bootstrap4" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type = "submit" class="btn btn-primary">Guncelle</button>
    </form>
  </div>
</div>

{% endblock body %}